<?php

return [
    [
        'name' => 'max_devices',
        'title' => '最大同时在线设备数',
        'type' => 'string',
        'content' => [],
        'value' => '3',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '允许 1～20 台设备，超过后自动踢掉最早登录的设备。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'device_token_cookie',
        'title' => '设备 Token Cookie',
        'type' => 'string',
        'content' => [],
        'value' => 'pfv_device_token',
        'rule' => 'required',
        'msg' => '',
        'tip' => '用于识别当前登录设备，请勿与其他 Cookie 重名。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'session_lifetime_days',
        'title' => '设备会话有效天数',
        'type' => 'string',
        'content' => [],
        'value' => '30',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '允许 1～365 天，到期后设备需要重新登录。',
        'ok' => '',
        'extend' => '',
    ],
];
