<?php

return [
    [
        'name' => 'douban_endpoint',
        'title' => '豆瓣数据接口',
        'type' => 'string',
        'content' => [],
        'value' => 'internal',
        'rule' => 'required',
        'msg' => '',
        'tip' => '默认 internal 使用插件内置网关；也可填写完整 URL，或以 / 开头并配合站点地址拼接。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'exclude_type_ids',
        'title' => '排除分类ID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '多个分类 ID 用英文逗号分隔。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'auto_confirm_score',
        'title' => '自动确认阈值',
        'type' => 'string',
        'content' => [],
        'value' => '85',
        'rule' => 'integer',
        'msg' => '',
        'tip' => '候选匹配达到该分数后才允许自动确认。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'request_per_minute',
        'title' => '豆瓣接口每分钟请求数',
        'type' => 'string',
        'content' => [],
        'value' => '30',
        'rule' => 'integer',
        'msg' => '',
        'tip' => '手动 Worker 批量运行时用于控制执行规模。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'max_attempts',
        'title' => '任务最大尝试次数',
        'type' => 'string',
        'content' => [],
        'value' => '5',
        'rule' => 'integer',
        'msg' => '',
        'tip' => '达到上限后任务进入 FAILED，需在后台确认后重新入队。',
        'ok' => '',
        'extend' => '',
    ],
];
