<?php

return [
    [
        'name' => 'batch_size',
        'title' => '每批扫描记录数',
        'type' => 'string',
        'content' => [],
        'value' => '200',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '单次查询扫描的影片条数，建议 100~500。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'max_items_per_scan',
        'title' => '单次扫描最大扫描总量',
        'type' => 'string',
        'content' => [],
        'value' => '0',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '0 表示扫描全部；建议上线时配置 0~10000。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'check_cover_head',
        'title' => '是否检测封面链接可达',
        'type' => 'string',
        'content' => [],
        'value' => '0',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '开启后会对封面 URL 发送 HEAD 请求，扫描更慢但更准确。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'cover_head_timeout',
        'title' => '封面链接检测超时（秒）',
        'type' => 'string',
        'content' => [],
        'value' => '3',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => 'HTTP HEAD 超时设置。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'duplicate_group_limit',
        'title' => '重复标题检测上限',
        'type' => 'string',
        'content' => [],
        'value' => '200',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '每次扫描最多检测多少个同名重复分组。',
        'ok' => '',
        'extend' => '',
    ],
];
