<?php

return [
    [
        'name' => 'home_limit',
        'title' => 'React 首页影片数',
        'type' => 'string',
        'content' => [],
        'value' => '120',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '首页按更新时间返回的最大影片数，允许 24～300；目录页使用独立的服务端分页。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'cache_seconds',
        'title' => '内容元数据缓存秒数',
        'type' => 'string',
        'content' => [],
        'value' => '300',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '允许 0～300 秒；缓存首页和分类统计，所有 HTTP 响应仍禁止共享缓存。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'summary_cache_seconds',
        'title' => '目录统计缓存秒数',
        'type' => 'string',
        'content' => [],
        'value' => '1800',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '允许 0～86400 秒；缓存按权限隔离的分类、筛选总数和剧情选项，避免翻页重复扫描影片表。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'comment_limit',
        'title' => '单个影片评论返回上限',
        'type' => 'string',
        'content' => [],
        'value' => '100',
        'rule' => 'required;integer',
        'msg' => '',
        'tip' => '只返回已审核评论，允许 1～200 条。',
        'ok' => '',
        'extend' => '',
    ],
];
